export const CREATED_PRODUCT = 'CREATE_PRODUCT';
export const BOUGHT_PRODUCT = 'BUY_PRODUCT';
export const SHIPPED_PRODUCT = 'SHIP_PRODUCT';
export const DELIVERED_PRODUCT = 'DELIVER_PRODUCT';
export const DELETED_PRODUCT = 'DELETED_PRODUCT';

export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const PRODUCTS_LIST_UPDATED = 'PRODUCTS_LIST_UPDATED';
